use std::fs;
use std::path::Path;

use super::{EmulatorTree, GlibcVersion};

fn v(s: &str) -> GlibcVersion {
    GlibcVersion::parse(s).unwrap()
}

#[test]
fn versions_compare_by_number_not_by_text() {
    assert!(v("2.2.5") < v("2.17"));
    assert!(v("2.17") < v("2.38"));
    assert_eq!(v("2.38").to_string(), "2.38");
    assert!(GlibcVersion::parse("PRIVATE").is_none());
}

#[test]
fn this_test_binary_needs_some_glibc_and_text_needs_none() {
    let me = fs::read(std::env::current_exe().unwrap()).unwrap();
    assert!(GlibcVersion::needed_by(&me).unwrap() >= Some(v("2.2.5")));
    assert_eq!(GlibcVersion::needed_by(b"not an ELF file").unwrap(), None);
}

/// The layout of experiment 115 §1.2, with this test binary as `eka2l1_qt`.
fn tree(root: &Path) {
    fs::create_dir_all(root.join("usr/bin")).unwrap();
    fs::copy(
        std::env::current_exe().unwrap(),
        root.join("usr/bin/eka2l1_qt"),
    )
    .unwrap();
    std::os::unix::fs::symlink("usr/bin/eka2l1_qt", root.join("AppRun")).unwrap();
    fs::write(
        root.join("usr/bin/qt.conf"),
        "# generated by linuxdeploy-plugin-qt\n[Paths]\nPrefix = ../\nPlugins = plugins\n",
    )
    .unwrap();
}

#[test]
fn the_observed_layout_is_accepted_and_its_floor_is_the_programs() {
    let tmp = tempfile::tempdir().unwrap();
    tree(tmp.path());
    let t = EmulatorTree::at(tmp.path()).unwrap();
    let me = fs::read(std::env::current_exe().unwrap()).unwrap();
    assert_eq!(
        Some(t.glibc_floor().unwrap()),
        GlibcVersion::needed_by(&me).unwrap()
    );
}

#[test]
fn an_apprun_that_is_not_the_link_is_refused() {
    let tmp = tempfile::tempdir().unwrap();
    tree(tmp.path());
    fs::remove_file(tmp.path().join("AppRun")).unwrap();
    fs::write(tmp.path().join("AppRun"), "#!/bin/sh\n").unwrap();
    let e = EmulatorTree::at(tmp.path()).err().unwrap().to_string();
    assert!(e.contains("AppRun"), "{e}");
}

#[test]
fn apprun_hooks_are_refused_until_observed() {
    let tmp = tempfile::tempdir().unwrap();
    tree(tmp.path());
    fs::create_dir(tmp.path().join("apprun-hooks")).unwrap();
    let e = EmulatorTree::at(tmp.path()).err().unwrap().to_string();
    assert!(e.contains("apprun-hooks"), "{e}");
}

#[test]
fn a_qt_conf_without_the_plugin_path_is_refused() {
    let tmp = tempfile::tempdir().unwrap();
    tree(tmp.path());
    fs::write(
        tmp.path().join("usr/bin/qt.conf"),
        "[Paths]\nPrefix = ../\n",
    )
    .unwrap();
    let e = EmulatorTree::at(tmp.path()).err().unwrap().to_string();
    assert!(e.contains("Plugins = plugins"), "{e}");
}
